# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


from typing import Union, Iterable
from Basilisk.utilities import pythonVariableLogger



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _prescribedRot2DOF
else:
    import _prescribedRot2DOF

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



from Basilisk.architecture.swig_common_model import *


def new_doubleArray(nelements):
    return _prescribedRot2DOF.new_doubleArray(nelements)

def delete_doubleArray(ary):
    return _prescribedRot2DOF.delete_doubleArray(ary)

def doubleArray_getitem(ary, index):
    return _prescribedRot2DOF.doubleArray_getitem(ary, index)

def doubleArray_setitem(ary, index, value):
    return _prescribedRot2DOF.doubleArray_setitem(ary, index, value)

def new_longArray(nelements):
    return _prescribedRot2DOF.new_longArray(nelements)

def delete_longArray(ary):
    return _prescribedRot2DOF.delete_longArray(ary)

def longArray_getitem(ary, index):
    return _prescribedRot2DOF.longArray_getitem(ary, index)

def longArray_setitem(ary, index, value):
    return _prescribedRot2DOF.longArray_setitem(ary, index, value)

def new_intArray(nelements):
    return _prescribedRot2DOF.new_intArray(nelements)

def delete_intArray(ary):
    return _prescribedRot2DOF.delete_intArray(ary)

def intArray_getitem(ary, index):
    return _prescribedRot2DOF.intArray_getitem(ary, index)

def intArray_setitem(ary, index, value):
    return _prescribedRot2DOF.intArray_setitem(ary, index, value)

def new_shortArray(nelements):
    return _prescribedRot2DOF.new_shortArray(nelements)

def delete_shortArray(ary):
    return _prescribedRot2DOF.delete_shortArray(ary)

def shortArray_getitem(ary, index):
    return _prescribedRot2DOF.shortArray_getitem(ary, index)

def shortArray_setitem(ary, index, value):
    return _prescribedRot2DOF.shortArray_setitem(ary, index, value)


def getStructSize(self):
    try:
        return eval('sizeof_' + repr(self).split(';')[0].split('.')[-1])
    except (NameError) as e:
        typeString = 'sizeof_' + repr(self).split(';')[0].split('.')[-1]
        raise NameError(e.message + '\nYou tried to get this size macro: ' + typeString + 
            '\n It appears to be undefined.  \nYou need to run the SWIG GEN_SIZEOF' +  
            ' SWIG macro against the class/struct in your SWIG file if you want to ' + 
            ' make this call.\n')


def protectSetAttr(self, name, value):
    if(hasattr(self, name) or name == 'this' or name.find('swig') >= 0):
        object.__setattr__(self, name, value)
    else:
        raise ValueError('You tried to add this variable: ' + name + '\n' + 
            'To this class: ' + str(self))

def protectAllClasses(moduleType):
    import inspect
    import sys
    clsmembers = inspect.getmembers(sys.modules[__name__], inspect.isclass)
    for member in clsmembers:
        try:
            exec(str(member[0]) + '.__setattr__ = protectSetAttr')
            exec(str(member[0]) + '.getStructSize = getStructSize') 
        except (AttributeError, TypeError) as e:
            pass


MAX_LOGGING_LENGTH = _prescribedRot2DOF.MAX_LOGGING_LENGTH
BSK_DEBUG = _prescribedRot2DOF.BSK_DEBUG
BSK_INFORMATION = _prescribedRot2DOF.BSK_INFORMATION
BSK_WARNING = _prescribedRot2DOF.BSK_WARNING
BSK_ERROR = _prescribedRot2DOF.BSK_ERROR
BSK_SILENT = _prescribedRot2DOF.BSK_SILENT

def printDefaultLogLevel():
    return _prescribedRot2DOF.printDefaultLogLevel()

def setDefaultLogLevel(logLevel):
    return _prescribedRot2DOF.setDefaultLogLevel(logLevel)

def getDefaultLogLevel():
    return _prescribedRot2DOF.getDefaultLogLevel()
class BSKLogger(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _prescribedRot2DOF.BSKLogger_swiginit(self, _prescribedRot2DOF.new_BSKLogger(*args))
    __swig_destroy__ = _prescribedRot2DOF.delete_BSKLogger

    def setLogLevel(self, logLevel):
        return _prescribedRot2DOF.BSKLogger_setLogLevel(self, logLevel)

    def printLogLevel(self):
        return _prescribedRot2DOF.BSKLogger_printLogLevel(self)

    def getLogLevel(self):
        return _prescribedRot2DOF.BSKLogger_getLogLevel(self)

    def bskLog(self, targetLevel, info):
        return _prescribedRot2DOF.BSKLogger_bskLog(self, targetLevel, info)
    logLevelMap = property(_prescribedRot2DOF.BSKLogger_logLevelMap_get, _prescribedRot2DOF.BSKLogger_logLevelMap_set)

# Register BSKLogger in _prescribedRot2DOF:
_prescribedRot2DOF.BSKLogger_swigregister(BSKLogger)
cvar = _prescribedRot2DOF.cvar


def _BSKLogger():
    return _prescribedRot2DOF._BSKLogger()

def _BSKLogger_d(arg1):
    return _prescribedRot2DOF._BSKLogger_d(arg1)

def _printLogLevel(arg1):
    return _prescribedRot2DOF._printLogLevel(arg1)

def _setLogLevel(arg1, arg2):
    return _prescribedRot2DOF._setLogLevel(arg1, arg2)

def _bskLog(arg1, arg2, arg3):
    return _prescribedRot2DOF._bskLog(arg1, arg2, arg3)
class SysModel(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _prescribedRot2DOF.SysModel_swiginit(self, _prescribedRot2DOF.new_SysModel(*args))
    __swig_destroy__ = _prescribedRot2DOF.delete_SysModel

    def SelfInit(self):
        return _prescribedRot2DOF.SysModel_SelfInit(self)

    def IntegratedInit(self):
        return _prescribedRot2DOF.SysModel_IntegratedInit(self)

    def UpdateState(self, CurrentSimNanos):
        return _prescribedRot2DOF.SysModel_UpdateState(self, CurrentSimNanos)

    def Reset(self, CurrentSimNanos):
        return _prescribedRot2DOF.SysModel_Reset(self, CurrentSimNanos)
    ModelTag = property(_prescribedRot2DOF.SysModel_ModelTag_get, _prescribedRot2DOF.SysModel_ModelTag_set)
    CallCounts = property(_prescribedRot2DOF.SysModel_CallCounts_get, _prescribedRot2DOF.SysModel_CallCounts_set)
    RNGSeed = property(_prescribedRot2DOF.SysModel_RNGSeed_get, _prescribedRot2DOF.SysModel_RNGSeed_set)
    moduleID = property(_prescribedRot2DOF.SysModel_moduleID_get, _prescribedRot2DOF.SysModel_moduleID_set)

    def logger(self, *args, **kwargs):
        raise TypeError(
            f"The 'logger' function is not supported for this type ('{type(self).__qualname__}'). "
            "To fix this, update the SWIG file for this module. Change "
            """'%include "sys_model.h"' to '%include "sys_model.i"'"""
        )


    def logger(self, variableNames: Union[str, Iterable[str]], recordingTime: int = 0):
        if isinstance(variableNames, str):
            variableNames = [variableNames]

        logging_functions = {
            variable_name: lambda _, vn=variable_name: getattr(self, vn)
            for variable_name in variableNames
        }

        for variable_name, log_fun in logging_functions.items():
            try:
                log_fun(0)
            except AttributeError:
                raise ValueError(f"Cannot log {variable_name} as it is not a "
                                f"variable of {type(self).__name__}")

        return pythonVariableLogger.PythonVariableLogger(logging_functions, recordingTime)


# Register SysModel in _prescribedRot2DOF:
_prescribedRot2DOF.SysModel_swigregister(SysModel)
class PrescribedRot2DOFConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    phiDDotMax = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_phiDDotMax_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_phiDDotMax_set)
    rotAxis1_M = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_rotAxis1_M_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_rotAxis1_M_set)
    rotAxis2_F1 = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_rotAxis2_F1_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_rotAxis2_F1_set)
    r_FM_M = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_r_FM_M_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_r_FM_M_set)
    rPrime_FM_M = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_rPrime_FM_M_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_rPrime_FM_M_set)
    rPrimePrime_FM_M = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_rPrimePrime_FM_M_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_rPrimePrime_FM_M_set)
    omega_FM_F = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_omega_FM_F_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_omega_FM_F_set)
    omegaPrime_FM_F = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_omegaPrime_FM_F_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_omegaPrime_FM_F_set)
    sigma_FM = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_sigma_FM_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_sigma_FM_set)
    isManeuverComplete = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_isManeuverComplete_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_isManeuverComplete_set)
    maneuverStartTime = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_maneuverStartTime_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_maneuverStartTime_set)
    rotAxis_M = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_rotAxis_M_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_rotAxis_M_set)
    phiRef = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_phiRef_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_phiRef_set)
    phiDotRef = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_phiDotRef_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_phiDotRef_set)
    phi = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_phi_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_phi_set)
    phiRefAccum = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_phiRefAccum_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_phiRefAccum_set)
    phiAccum = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_phiAccum_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_phiAccum_set)
    maneuverSwitchTime = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_maneuverSwitchTime_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_maneuverSwitchTime_set)
    maneuverEndTime = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_maneuverEndTime_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_maneuverEndTime_set)
    a = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_a_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_a_set)
    b = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_b_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_b_set)
    dcm_F0M = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_dcm_F0M_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_dcm_F0M_set)
    spinningBodyRef1InMsg = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_spinningBodyRef1InMsg_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_spinningBodyRef1InMsg_set)
    spinningBodyRef2InMsg = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_spinningBodyRef2InMsg_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_spinningBodyRef2InMsg_set)
    prescribedMotionOutMsg = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_prescribedMotionOutMsg_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_prescribedMotionOutMsg_set)
    bskLogger = property(_prescribedRot2DOF.PrescribedRot2DOFConfig_bskLogger_get, _prescribedRot2DOF.PrescribedRot2DOFConfig_bskLogger_set)

    def createWrapper(self):
        return prescribedRot2DOF(self)


    def __init__(self):
        _prescribedRot2DOF.PrescribedRot2DOFConfig_swiginit(self, _prescribedRot2DOF.new_PrescribedRot2DOFConfig())
    __swig_destroy__ = _prescribedRot2DOF.delete_PrescribedRot2DOFConfig

# Register PrescribedRot2DOFConfig in _prescribedRot2DOF:
_prescribedRot2DOF.PrescribedRot2DOFConfig_swigregister(PrescribedRot2DOFConfig)
class prescribedRot2DOF(SysModel):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _prescribedRot2DOF.prescribedRot2DOF_swiginit(self, _prescribedRot2DOF.new_prescribedRot2DOF(*args))

        if (len(args)) > 0:
            args[0].thisown = False




    def SelfInit(self):
        return _prescribedRot2DOF.prescribedRot2DOF_SelfInit(self)

    def UpdateState(self, currentSimNanos):
        return _prescribedRot2DOF.prescribedRot2DOF_UpdateState(self, currentSimNanos)

    def Reset(self, currentSimNanos):
        return _prescribedRot2DOF.prescribedRot2DOF_Reset(self, currentSimNanos)

    def __deref__(self):
        return _prescribedRot2DOF.prescribedRot2DOF___deref__(self)

    def getConfig(self):
        return _prescribedRot2DOF.prescribedRot2DOF_getConfig(self)
    __swig_destroy__ = _prescribedRot2DOF.delete_prescribedRot2DOF
    phiDDotMax = property(_prescribedRot2DOF.prescribedRot2DOF_phiDDotMax_get, _prescribedRot2DOF.prescribedRot2DOF_phiDDotMax_set)
    rotAxis1_M = property(_prescribedRot2DOF.prescribedRot2DOF_rotAxis1_M_get, _prescribedRot2DOF.prescribedRot2DOF_rotAxis1_M_set)
    rotAxis2_F1 = property(_prescribedRot2DOF.prescribedRot2DOF_rotAxis2_F1_get, _prescribedRot2DOF.prescribedRot2DOF_rotAxis2_F1_set)
    r_FM_M = property(_prescribedRot2DOF.prescribedRot2DOF_r_FM_M_get, _prescribedRot2DOF.prescribedRot2DOF_r_FM_M_set)
    rPrime_FM_M = property(_prescribedRot2DOF.prescribedRot2DOF_rPrime_FM_M_get, _prescribedRot2DOF.prescribedRot2DOF_rPrime_FM_M_set)
    rPrimePrime_FM_M = property(_prescribedRot2DOF.prescribedRot2DOF_rPrimePrime_FM_M_get, _prescribedRot2DOF.prescribedRot2DOF_rPrimePrime_FM_M_set)
    omega_FM_F = property(_prescribedRot2DOF.prescribedRot2DOF_omega_FM_F_get, _prescribedRot2DOF.prescribedRot2DOF_omega_FM_F_set)
    omegaPrime_FM_F = property(_prescribedRot2DOF.prescribedRot2DOF_omegaPrime_FM_F_get, _prescribedRot2DOF.prescribedRot2DOF_omegaPrime_FM_F_set)
    sigma_FM = property(_prescribedRot2DOF.prescribedRot2DOF_sigma_FM_get, _prescribedRot2DOF.prescribedRot2DOF_sigma_FM_set)
    isManeuverComplete = property(_prescribedRot2DOF.prescribedRot2DOF_isManeuverComplete_get, _prescribedRot2DOF.prescribedRot2DOF_isManeuverComplete_set)
    maneuverStartTime = property(_prescribedRot2DOF.prescribedRot2DOF_maneuverStartTime_get, _prescribedRot2DOF.prescribedRot2DOF_maneuverStartTime_set)
    rotAxis_M = property(_prescribedRot2DOF.prescribedRot2DOF_rotAxis_M_get, _prescribedRot2DOF.prescribedRot2DOF_rotAxis_M_set)
    phiRef = property(_prescribedRot2DOF.prescribedRot2DOF_phiRef_get, _prescribedRot2DOF.prescribedRot2DOF_phiRef_set)
    phiDotRef = property(_prescribedRot2DOF.prescribedRot2DOF_phiDotRef_get, _prescribedRot2DOF.prescribedRot2DOF_phiDotRef_set)
    phi = property(_prescribedRot2DOF.prescribedRot2DOF_phi_get, _prescribedRot2DOF.prescribedRot2DOF_phi_set)
    phiRefAccum = property(_prescribedRot2DOF.prescribedRot2DOF_phiRefAccum_get, _prescribedRot2DOF.prescribedRot2DOF_phiRefAccum_set)
    phiAccum = property(_prescribedRot2DOF.prescribedRot2DOF_phiAccum_get, _prescribedRot2DOF.prescribedRot2DOF_phiAccum_set)
    maneuverSwitchTime = property(_prescribedRot2DOF.prescribedRot2DOF_maneuverSwitchTime_get, _prescribedRot2DOF.prescribedRot2DOF_maneuverSwitchTime_set)
    maneuverEndTime = property(_prescribedRot2DOF.prescribedRot2DOF_maneuverEndTime_get, _prescribedRot2DOF.prescribedRot2DOF_maneuverEndTime_set)
    a = property(_prescribedRot2DOF.prescribedRot2DOF_a_get, _prescribedRot2DOF.prescribedRot2DOF_a_set)
    b = property(_prescribedRot2DOF.prescribedRot2DOF_b_get, _prescribedRot2DOF.prescribedRot2DOF_b_set)
    dcm_F0M = property(_prescribedRot2DOF.prescribedRot2DOF_dcm_F0M_get, _prescribedRot2DOF.prescribedRot2DOF_dcm_F0M_set)
    spinningBodyRef1InMsg = property(_prescribedRot2DOF.prescribedRot2DOF_spinningBodyRef1InMsg_get, _prescribedRot2DOF.prescribedRot2DOF_spinningBodyRef1InMsg_set)
    spinningBodyRef2InMsg = property(_prescribedRot2DOF.prescribedRot2DOF_spinningBodyRef2InMsg_get, _prescribedRot2DOF.prescribedRot2DOF_spinningBodyRef2InMsg_set)
    prescribedMotionOutMsg = property(_prescribedRot2DOF.prescribedRot2DOF_prescribedMotionOutMsg_get, _prescribedRot2DOF.prescribedRot2DOF_prescribedMotionOutMsg_set)
    bskLogger = property(_prescribedRot2DOF.prescribedRot2DOF_bskLogger_get, _prescribedRot2DOF.prescribedRot2DOF_bskLogger_set)

# Register prescribedRot2DOF in _prescribedRot2DOF:
_prescribedRot2DOF.prescribedRot2DOF_swigregister(prescribedRot2DOF)
class HingedRigidBodyMsgPayload(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    theta = property(_prescribedRot2DOF.HingedRigidBodyMsgPayload_theta_get, _prescribedRot2DOF.HingedRigidBodyMsgPayload_theta_set)
    thetaDot = property(_prescribedRot2DOF.HingedRigidBodyMsgPayload_thetaDot_get, _prescribedRot2DOF.HingedRigidBodyMsgPayload_thetaDot_set)

    def __init__(self):
        _prescribedRot2DOF.HingedRigidBodyMsgPayload_swiginit(self, _prescribedRot2DOF.new_HingedRigidBodyMsgPayload())
    __swig_destroy__ = _prescribedRot2DOF.delete_HingedRigidBodyMsgPayload

# Register HingedRigidBodyMsgPayload in _prescribedRot2DOF:
_prescribedRot2DOF.HingedRigidBodyMsgPayload_swigregister(HingedRigidBodyMsgPayload)
class PrescribedMotionMsgPayload(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    r_FM_M = property(_prescribedRot2DOF.PrescribedMotionMsgPayload_r_FM_M_get, _prescribedRot2DOF.PrescribedMotionMsgPayload_r_FM_M_set)
    rPrime_FM_M = property(_prescribedRot2DOF.PrescribedMotionMsgPayload_rPrime_FM_M_get, _prescribedRot2DOF.PrescribedMotionMsgPayload_rPrime_FM_M_set)
    rPrimePrime_FM_M = property(_prescribedRot2DOF.PrescribedMotionMsgPayload_rPrimePrime_FM_M_get, _prescribedRot2DOF.PrescribedMotionMsgPayload_rPrimePrime_FM_M_set)
    omega_FM_F = property(_prescribedRot2DOF.PrescribedMotionMsgPayload_omega_FM_F_get, _prescribedRot2DOF.PrescribedMotionMsgPayload_omega_FM_F_set)
    omegaPrime_FM_F = property(_prescribedRot2DOF.PrescribedMotionMsgPayload_omegaPrime_FM_F_get, _prescribedRot2DOF.PrescribedMotionMsgPayload_omegaPrime_FM_F_set)
    sigma_FM = property(_prescribedRot2DOF.PrescribedMotionMsgPayload_sigma_FM_get, _prescribedRot2DOF.PrescribedMotionMsgPayload_sigma_FM_set)

    def __init__(self):
        _prescribedRot2DOF.PrescribedMotionMsgPayload_swiginit(self, _prescribedRot2DOF.new_PrescribedMotionMsgPayload())
    __swig_destroy__ = _prescribedRot2DOF.delete_PrescribedMotionMsgPayload

# Register PrescribedMotionMsgPayload in _prescribedRot2DOF:
_prescribedRot2DOF.PrescribedMotionMsgPayload_swigregister(PrescribedMotionMsgPayload)

import sys
protectAllClasses(sys.modules[__name__])


