# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


from typing import Union, Iterable
from Basilisk.utilities import pythonVariableLogger



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _prescribedTrans
else:
    import _prescribedTrans

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



from Basilisk.architecture.swig_common_model import *


def new_doubleArray(nelements):
    return _prescribedTrans.new_doubleArray(nelements)

def delete_doubleArray(ary):
    return _prescribedTrans.delete_doubleArray(ary)

def doubleArray_getitem(ary, index):
    return _prescribedTrans.doubleArray_getitem(ary, index)

def doubleArray_setitem(ary, index, value):
    return _prescribedTrans.doubleArray_setitem(ary, index, value)

def new_longArray(nelements):
    return _prescribedTrans.new_longArray(nelements)

def delete_longArray(ary):
    return _prescribedTrans.delete_longArray(ary)

def longArray_getitem(ary, index):
    return _prescribedTrans.longArray_getitem(ary, index)

def longArray_setitem(ary, index, value):
    return _prescribedTrans.longArray_setitem(ary, index, value)

def new_intArray(nelements):
    return _prescribedTrans.new_intArray(nelements)

def delete_intArray(ary):
    return _prescribedTrans.delete_intArray(ary)

def intArray_getitem(ary, index):
    return _prescribedTrans.intArray_getitem(ary, index)

def intArray_setitem(ary, index, value):
    return _prescribedTrans.intArray_setitem(ary, index, value)

def new_shortArray(nelements):
    return _prescribedTrans.new_shortArray(nelements)

def delete_shortArray(ary):
    return _prescribedTrans.delete_shortArray(ary)

def shortArray_getitem(ary, index):
    return _prescribedTrans.shortArray_getitem(ary, index)

def shortArray_setitem(ary, index, value):
    return _prescribedTrans.shortArray_setitem(ary, index, value)


def getStructSize(self):
    try:
        return eval('sizeof_' + repr(self).split(';')[0].split('.')[-1])
    except (NameError) as e:
        typeString = 'sizeof_' + repr(self).split(';')[0].split('.')[-1]
        raise NameError(e.message + '\nYou tried to get this size macro: ' + typeString + 
            '\n It appears to be undefined.  \nYou need to run the SWIG GEN_SIZEOF' +  
            ' SWIG macro against the class/struct in your SWIG file if you want to ' + 
            ' make this call.\n')


def protectSetAttr(self, name, value):
    if(hasattr(self, name) or name == 'this' or name.find('swig') >= 0):
        object.__setattr__(self, name, value)
    else:
        raise ValueError('You tried to add this variable: ' + name + '\n' + 
            'To this class: ' + str(self))

def protectAllClasses(moduleType):
    import inspect
    import sys
    clsmembers = inspect.getmembers(sys.modules[__name__], inspect.isclass)
    for member in clsmembers:
        try:
            exec(str(member[0]) + '.__setattr__ = protectSetAttr')
            exec(str(member[0]) + '.getStructSize = getStructSize') 
        except (AttributeError, TypeError) as e:
            pass


MAX_LOGGING_LENGTH = _prescribedTrans.MAX_LOGGING_LENGTH
BSK_DEBUG = _prescribedTrans.BSK_DEBUG
BSK_INFORMATION = _prescribedTrans.BSK_INFORMATION
BSK_WARNING = _prescribedTrans.BSK_WARNING
BSK_ERROR = _prescribedTrans.BSK_ERROR
BSK_SILENT = _prescribedTrans.BSK_SILENT

def printDefaultLogLevel():
    return _prescribedTrans.printDefaultLogLevel()

def setDefaultLogLevel(logLevel):
    return _prescribedTrans.setDefaultLogLevel(logLevel)

def getDefaultLogLevel():
    return _prescribedTrans.getDefaultLogLevel()
class BSKLogger(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _prescribedTrans.BSKLogger_swiginit(self, _prescribedTrans.new_BSKLogger(*args))
    __swig_destroy__ = _prescribedTrans.delete_BSKLogger

    def setLogLevel(self, logLevel):
        return _prescribedTrans.BSKLogger_setLogLevel(self, logLevel)

    def printLogLevel(self):
        return _prescribedTrans.BSKLogger_printLogLevel(self)

    def getLogLevel(self):
        return _prescribedTrans.BSKLogger_getLogLevel(self)

    def bskLog(self, targetLevel, info):
        return _prescribedTrans.BSKLogger_bskLog(self, targetLevel, info)
    logLevelMap = property(_prescribedTrans.BSKLogger_logLevelMap_get, _prescribedTrans.BSKLogger_logLevelMap_set)

# Register BSKLogger in _prescribedTrans:
_prescribedTrans.BSKLogger_swigregister(BSKLogger)
cvar = _prescribedTrans.cvar


def _BSKLogger():
    return _prescribedTrans._BSKLogger()

def _BSKLogger_d(arg1):
    return _prescribedTrans._BSKLogger_d(arg1)

def _printLogLevel(arg1):
    return _prescribedTrans._printLogLevel(arg1)

def _setLogLevel(arg1, arg2):
    return _prescribedTrans._setLogLevel(arg1, arg2)

def _bskLog(arg1, arg2, arg3):
    return _prescribedTrans._bskLog(arg1, arg2, arg3)
class SysModel(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _prescribedTrans.SysModel_swiginit(self, _prescribedTrans.new_SysModel(*args))
    __swig_destroy__ = _prescribedTrans.delete_SysModel

    def SelfInit(self):
        return _prescribedTrans.SysModel_SelfInit(self)

    def IntegratedInit(self):
        return _prescribedTrans.SysModel_IntegratedInit(self)

    def UpdateState(self, CurrentSimNanos):
        return _prescribedTrans.SysModel_UpdateState(self, CurrentSimNanos)

    def Reset(self, CurrentSimNanos):
        return _prescribedTrans.SysModel_Reset(self, CurrentSimNanos)
    ModelTag = property(_prescribedTrans.SysModel_ModelTag_get, _prescribedTrans.SysModel_ModelTag_set)
    CallCounts = property(_prescribedTrans.SysModel_CallCounts_get, _prescribedTrans.SysModel_CallCounts_set)
    RNGSeed = property(_prescribedTrans.SysModel_RNGSeed_get, _prescribedTrans.SysModel_RNGSeed_set)
    moduleID = property(_prescribedTrans.SysModel_moduleID_get, _prescribedTrans.SysModel_moduleID_set)

    def logger(self, *args, **kwargs):
        raise TypeError(
            f"The 'logger' function is not supported for this type ('{type(self).__qualname__}'). "
            "To fix this, update the SWIG file for this module. Change "
            """'%include "sys_model.h"' to '%include "sys_model.i"'"""
        )


    def logger(self, variableNames: Union[str, Iterable[str]], recordingTime: int = 0):
        if isinstance(variableNames, str):
            variableNames = [variableNames]

        logging_functions = {
            variable_name: lambda _, vn=variable_name: getattr(self, vn)
            for variable_name in variableNames
        }

        for variable_name, log_fun in logging_functions.items():
            try:
                log_fun(0)
            except AttributeError:
                raise ValueError(f"Cannot log {variable_name} as it is not a "
                                f"variable of {type(self).__name__}")

        return pythonVariableLogger.PythonVariableLogger(logging_functions, recordingTime)


# Register SysModel in _prescribedTrans:
_prescribedTrans.SysModel_swigregister(SysModel)
class PrescribedTransConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    scalarAccelMax = property(_prescribedTrans.PrescribedTransConfig_scalarAccelMax_get, _prescribedTrans.PrescribedTransConfig_scalarAccelMax_set)
    transAxis_M = property(_prescribedTrans.PrescribedTransConfig_transAxis_M_get, _prescribedTrans.PrescribedTransConfig_transAxis_M_set)
    r_FM_M = property(_prescribedTrans.PrescribedTransConfig_r_FM_M_get, _prescribedTrans.PrescribedTransConfig_r_FM_M_set)
    rPrime_FM_M = property(_prescribedTrans.PrescribedTransConfig_rPrime_FM_M_get, _prescribedTrans.PrescribedTransConfig_rPrime_FM_M_set)
    rPrimePrime_FM_M = property(_prescribedTrans.PrescribedTransConfig_rPrimePrime_FM_M_get, _prescribedTrans.PrescribedTransConfig_rPrimePrime_FM_M_set)
    omega_FM_F = property(_prescribedTrans.PrescribedTransConfig_omega_FM_F_get, _prescribedTrans.PrescribedTransConfig_omega_FM_F_set)
    omegaPrime_FM_F = property(_prescribedTrans.PrescribedTransConfig_omegaPrime_FM_F_get, _prescribedTrans.PrescribedTransConfig_omegaPrime_FM_F_set)
    sigma_FM = property(_prescribedTrans.PrescribedTransConfig_sigma_FM_get, _prescribedTrans.PrescribedTransConfig_sigma_FM_set)
    convergence = property(_prescribedTrans.PrescribedTransConfig_convergence_get, _prescribedTrans.PrescribedTransConfig_convergence_set)
    tInit = property(_prescribedTrans.PrescribedTransConfig_tInit_get, _prescribedTrans.PrescribedTransConfig_tInit_set)
    scalarPosInit = property(_prescribedTrans.PrescribedTransConfig_scalarPosInit_get, _prescribedTrans.PrescribedTransConfig_scalarPosInit_set)
    scalarVelInit = property(_prescribedTrans.PrescribedTransConfig_scalarVelInit_get, _prescribedTrans.PrescribedTransConfig_scalarVelInit_set)
    scalarPosRef = property(_prescribedTrans.PrescribedTransConfig_scalarPosRef_get, _prescribedTrans.PrescribedTransConfig_scalarPosRef_set)
    scalarVelRef = property(_prescribedTrans.PrescribedTransConfig_scalarVelRef_get, _prescribedTrans.PrescribedTransConfig_scalarVelRef_set)
    ts = property(_prescribedTrans.PrescribedTransConfig_ts_get, _prescribedTrans.PrescribedTransConfig_ts_set)
    tf = property(_prescribedTrans.PrescribedTransConfig_tf_get, _prescribedTrans.PrescribedTransConfig_tf_set)
    a = property(_prescribedTrans.PrescribedTransConfig_a_get, _prescribedTrans.PrescribedTransConfig_a_set)
    b = property(_prescribedTrans.PrescribedTransConfig_b_get, _prescribedTrans.PrescribedTransConfig_b_set)
    prescribedTransInMsg = property(_prescribedTrans.PrescribedTransConfig_prescribedTransInMsg_get, _prescribedTrans.PrescribedTransConfig_prescribedTransInMsg_set)
    prescribedMotionOutMsg = property(_prescribedTrans.PrescribedTransConfig_prescribedMotionOutMsg_get, _prescribedTrans.PrescribedTransConfig_prescribedMotionOutMsg_set)
    bskLogger = property(_prescribedTrans.PrescribedTransConfig_bskLogger_get, _prescribedTrans.PrescribedTransConfig_bskLogger_set)

    def createWrapper(self):
        return prescribedTrans(self)


    def __init__(self):
        _prescribedTrans.PrescribedTransConfig_swiginit(self, _prescribedTrans.new_PrescribedTransConfig())
    __swig_destroy__ = _prescribedTrans.delete_PrescribedTransConfig

# Register PrescribedTransConfig in _prescribedTrans:
_prescribedTrans.PrescribedTransConfig_swigregister(PrescribedTransConfig)
class prescribedTrans(SysModel):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _prescribedTrans.prescribedTrans_swiginit(self, _prescribedTrans.new_prescribedTrans(*args))

        if (len(args)) > 0:
            args[0].thisown = False




    def SelfInit(self):
        return _prescribedTrans.prescribedTrans_SelfInit(self)

    def UpdateState(self, currentSimNanos):
        return _prescribedTrans.prescribedTrans_UpdateState(self, currentSimNanos)

    def Reset(self, currentSimNanos):
        return _prescribedTrans.prescribedTrans_Reset(self, currentSimNanos)

    def __deref__(self):
        return _prescribedTrans.prescribedTrans___deref__(self)

    def getConfig(self):
        return _prescribedTrans.prescribedTrans_getConfig(self)
    __swig_destroy__ = _prescribedTrans.delete_prescribedTrans
    scalarAccelMax = property(_prescribedTrans.prescribedTrans_scalarAccelMax_get, _prescribedTrans.prescribedTrans_scalarAccelMax_set)
    transAxis_M = property(_prescribedTrans.prescribedTrans_transAxis_M_get, _prescribedTrans.prescribedTrans_transAxis_M_set)
    r_FM_M = property(_prescribedTrans.prescribedTrans_r_FM_M_get, _prescribedTrans.prescribedTrans_r_FM_M_set)
    rPrime_FM_M = property(_prescribedTrans.prescribedTrans_rPrime_FM_M_get, _prescribedTrans.prescribedTrans_rPrime_FM_M_set)
    rPrimePrime_FM_M = property(_prescribedTrans.prescribedTrans_rPrimePrime_FM_M_get, _prescribedTrans.prescribedTrans_rPrimePrime_FM_M_set)
    omega_FM_F = property(_prescribedTrans.prescribedTrans_omega_FM_F_get, _prescribedTrans.prescribedTrans_omega_FM_F_set)
    omegaPrime_FM_F = property(_prescribedTrans.prescribedTrans_omegaPrime_FM_F_get, _prescribedTrans.prescribedTrans_omegaPrime_FM_F_set)
    sigma_FM = property(_prescribedTrans.prescribedTrans_sigma_FM_get, _prescribedTrans.prescribedTrans_sigma_FM_set)
    convergence = property(_prescribedTrans.prescribedTrans_convergence_get, _prescribedTrans.prescribedTrans_convergence_set)
    tInit = property(_prescribedTrans.prescribedTrans_tInit_get, _prescribedTrans.prescribedTrans_tInit_set)
    scalarPosInit = property(_prescribedTrans.prescribedTrans_scalarPosInit_get, _prescribedTrans.prescribedTrans_scalarPosInit_set)
    scalarVelInit = property(_prescribedTrans.prescribedTrans_scalarVelInit_get, _prescribedTrans.prescribedTrans_scalarVelInit_set)
    scalarPosRef = property(_prescribedTrans.prescribedTrans_scalarPosRef_get, _prescribedTrans.prescribedTrans_scalarPosRef_set)
    scalarVelRef = property(_prescribedTrans.prescribedTrans_scalarVelRef_get, _prescribedTrans.prescribedTrans_scalarVelRef_set)
    ts = property(_prescribedTrans.prescribedTrans_ts_get, _prescribedTrans.prescribedTrans_ts_set)
    tf = property(_prescribedTrans.prescribedTrans_tf_get, _prescribedTrans.prescribedTrans_tf_set)
    a = property(_prescribedTrans.prescribedTrans_a_get, _prescribedTrans.prescribedTrans_a_set)
    b = property(_prescribedTrans.prescribedTrans_b_get, _prescribedTrans.prescribedTrans_b_set)
    prescribedTransInMsg = property(_prescribedTrans.prescribedTrans_prescribedTransInMsg_get, _prescribedTrans.prescribedTrans_prescribedTransInMsg_set)
    prescribedMotionOutMsg = property(_prescribedTrans.prescribedTrans_prescribedMotionOutMsg_get, _prescribedTrans.prescribedTrans_prescribedMotionOutMsg_set)
    bskLogger = property(_prescribedTrans.prescribedTrans_bskLogger_get, _prescribedTrans.prescribedTrans_bskLogger_set)

# Register prescribedTrans in _prescribedTrans:
_prescribedTrans.prescribedTrans_swigregister(prescribedTrans)
class PrescribedMotionMsgPayload(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    r_FM_M = property(_prescribedTrans.PrescribedMotionMsgPayload_r_FM_M_get, _prescribedTrans.PrescribedMotionMsgPayload_r_FM_M_set)
    rPrime_FM_M = property(_prescribedTrans.PrescribedMotionMsgPayload_rPrime_FM_M_get, _prescribedTrans.PrescribedMotionMsgPayload_rPrime_FM_M_set)
    rPrimePrime_FM_M = property(_prescribedTrans.PrescribedMotionMsgPayload_rPrimePrime_FM_M_get, _prescribedTrans.PrescribedMotionMsgPayload_rPrimePrime_FM_M_set)
    omega_FM_F = property(_prescribedTrans.PrescribedMotionMsgPayload_omega_FM_F_get, _prescribedTrans.PrescribedMotionMsgPayload_omega_FM_F_set)
    omegaPrime_FM_F = property(_prescribedTrans.PrescribedMotionMsgPayload_omegaPrime_FM_F_get, _prescribedTrans.PrescribedMotionMsgPayload_omegaPrime_FM_F_set)
    sigma_FM = property(_prescribedTrans.PrescribedMotionMsgPayload_sigma_FM_get, _prescribedTrans.PrescribedMotionMsgPayload_sigma_FM_set)

    def __init__(self):
        _prescribedTrans.PrescribedMotionMsgPayload_swiginit(self, _prescribedTrans.new_PrescribedMotionMsgPayload())
    __swig_destroy__ = _prescribedTrans.delete_PrescribedMotionMsgPayload

# Register PrescribedMotionMsgPayload in _prescribedTrans:
_prescribedTrans.PrescribedMotionMsgPayload_swigregister(PrescribedMotionMsgPayload)
class PrescribedTransMsgPayload(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    scalarPos = property(_prescribedTrans.PrescribedTransMsgPayload_scalarPos_get, _prescribedTrans.PrescribedTransMsgPayload_scalarPos_set)
    scalarVel = property(_prescribedTrans.PrescribedTransMsgPayload_scalarVel_get, _prescribedTrans.PrescribedTransMsgPayload_scalarVel_set)

    def __init__(self):
        _prescribedTrans.PrescribedTransMsgPayload_swiginit(self, _prescribedTrans.new_PrescribedTransMsgPayload())
    __swig_destroy__ = _prescribedTrans.delete_PrescribedTransMsgPayload

# Register PrescribedTransMsgPayload in _prescribedTrans:
_prescribedTrans.PrescribedTransMsgPayload_swigregister(PrescribedTransMsgPayload)

import sys
protectAllClasses(sys.modules[__name__])


